<?php
$helper         = $this->helper("Lof\Formbuilder\Helper\Fields");
$helper_data = $this->helper("Lof\Formbuilder\Helper\Data");
$form           = $block->getForm();
$form_data      = $this->getData('form_data');
$field          = $this->getData('field_data');
$field_type     = $field['field_type'];
$label          = $block->filterMessage($field['label']);
$options        = $field['field_options'];
$required       = $field['required'];
$cid              = $helper_data->getFieldId($field);
$frame_work_css = '';
if(isset($field['frame_work_css'])) {
	$frame_work_css	  = $field['frame_work_css'];
}
$field_name        = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$available_fields = $helper->getAvailableFields();
$html             = '';
$field_validate   = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates        = $field_validate;
$field_help 	  = isset($options['description'])?$block->filterMessage($options['description']):'';
$inlineCss        = isset($field['inline_css'])?$field['inline_css']:'';

$color_label 	  = isset($options['color_label'])?'color:'.$options['color_label'].';':'';
$color_text 	  = isset($options['color_text'])?'color:'.$options['color_text'].';':'';
$color_description= isset($options['color_description'])?'color:'.$options['color_description'].';':'';
$background_color = isset($options['background_color'])?'background-color:'.$options['background_color'].';':'';

$border_width         = isset($options['border_width'])?'border-width:'.(int)$options['border_width'].'px;':'';
$border_radius        = isset($options['border_radius'])?'border-radius:'.(int)$options['border_radius'].'px;':'';
$border_color         = isset($options['border_color'])?'border-color:'.$options['border_color'].';':'';
$border_style         = isset($options['border_style'])?'border-style:'.$options['border_style'].';':'';
$font_size            = isset($options['font_size'])?'font-size:'.(int)$options['font_size'].'px;':'';
$font_style           = isset($options['font_style'])?'font-style:'.$options['font_style'].';':'';
$font_weight          = isset($options['font_weight'])?'font-weight:'.$options['font_weight'].';':'';

$font_size 		  = isset($options['font_size'])?'font-size:'.(int)$options['font_size'].'px;':'';
$font_style 	  = isset($options['font_style'])?'font-style:'.$options['font_style'].';':'';
$font_weight	  = isset($options['font_weight'])?'font-weight:'.$options['font_weight'].';':'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
if($frame_work_css == 'foundation') {
	$medium = 'columns medium-';
}else{
	$medium = 'col-sm-';
}
?>
<div class="subtemplate-wrapper" style="<?php echo $inlineCss ?>">
	<label for="<?php echo $field_id; ?>" style="<?php echo $font_size.$font_style.$font_weight.$color_label; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
	<div class="row">
		<div class="input-box <?php echo isset($field['fieldcol'])?$medium.$field['fieldcol']:$medium.'12'; ?>">
			<?php
			if($options['options']) { ?>
				<select style="<?php echo $color_text.$background_color.$border_width.$border_radius.$border_color.$border_style; ?>" name="<?php echo $field_name; ?>" id="<?php echo $field_id; ?>" class="<?php echo (1==$required)?'required-entry':''; ?> <?php echo $validates; ?>">
					<?php if(isset($options['include_blank_option']) && $options['include_blank_option']) { ?>
						<option value=""></option>
						<?php } ?>
						<?php foreach($options['options'] as $key=>$val) {
							$item_label = $val['label'];
							$item_checked = $val['checked'];
							if($form_data && isset($form_data[$field_name]) && $form_data[$field_name] == $item_label){
								$item_checked = true;
							}
							$item_label2 = $block->filterMessage($item_label);
							?>
							<option style="<?php echo $color_text.$background_color.$border_width.$border_radius.$border_color.$border_style; ?>" value="<?php echo $block->escapeQuote($item_label); ?>" <?php echo ($item_checked)?'selected="selected"':''; ?>><?php echo __($item_label2); ?></option>
							<?php } ?>
						</select>
						<?php }
						?>
						<?php if($field_help) { ?>
							<span class="help-block" style="<?php echo $color_description; ?>"><?php echo $field_help ?></span>
							<?php } ?>
						</div>
					</div>
				</div>