<?php
$helper           = $this->helper("Lof\Formbuilder\Helper\Fields");
$dataHelper       = $this->helper("Lof\Formbuilder\Helper\Data");
$form             = $block->getForm();
$form_data        = $this->getData('form_data');
$field            = $this->getData('field_data');
$field_type       = $field['field_type'];
$label            = $block->filterMessage($field['label']);
$options          = $field['field_options'];
$required         = $field['required'];
$cid              = $dataHelper->getFieldId($field);
$field_name       = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$available_fields = $helper->getAvailableFields();
$field_validate   = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates        = $field_validate;
$field_help 	  = isset($options['description'])?$block->filterMessage($options['description']):'';
$inlineCss        = isset($field['inline_css'])?$field['inline_css']:'';
if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$limit = isset($field['limit'])?(int)$field['limit']:5;
$default = isset($field['default'])?(float)$field['default']:0;
?>
<div class="subtemplate-wrapper" style="<?php echo $inlineCss ?>">
	<label for="<?php echo $field_id; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
	<div class="input-box">
		<input name="<?php echo $field_name; ?>" id="<?php echo $field_id; ?>" title="<?php echo $label; ?>" value="<?php echo ($form_data && isset($form_data[$field_name]))?$form_data[$field_name]:''; ?>" class="input-text <?php echo (1==$required)?'required-entry':''; ?>" type="hidden"/>
		<input name="<?php echo $field_name."_limit"; ?>" id="<?php echo $field_id."_limit"; ?>" title="<?php echo $label; ?>" value="<?php echo $limit; ?>" class="input-text" type="hidden"/>
		<div id="<?php echo $field_id."_rating"; ?>" class="ves-rating-play"></div>
		<script type="text/javascript">
			require(['jquery', 'Lof_Formbuilder/js/raty/raty'], function(){
				jQuery('#<?php echo $field_id."_rating"; ?>').raty({
					path: '<?php echo $dataHelper->getMediaUrl()."lof/formbuilder/rating/"; ?>',
					score: <?php echo $default; ?>,
					number: <?php echo $limit; ?>,
					targetScore: '#<?php echo $field_id; ?>',
					click: function(score, evt) {
						jQuery('#<?php echo $field_id; ?>').val(score);
						return false;
					}
				});
			});
		</script>
		<?php if($field_help) { ?>
		<span class="help-block"><?php echo $field_help; ?></span>
		<?php } ?>
	</div>
</div>