<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>

<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Customer Login') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Mobile/Email') ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="text" class="input-text emailandmob" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true}" placeholder="mobile/username">
                        <!-- magecomp start -->
                        <div for="email"  style="color:#e02b27;display:none; font-size: 1.2rem;" id="custom-email-error" >Please Enter Valid Username</div>
                        <!-- magecomp end -->
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/javascript">
require(['jquery'],function() { 
    jQuery(document).ready(function(e) {
    	
        jQuery('#login-form').submit(function() {
    		var username = jQuery("#email").val();
    		jQuery("#custom-email-error").css('display','none');
    		jQuery("#email").removeClass("mage-error");
    		if(jQuery.isNumeric(username)){
    			if(username.length < 10 ){
    				jQuery("#custom-email-error").css('display','block');
    				jQuery("#email").addClass("mage-error");
    				return false;
    			}
    		}
    		else if(!isEmail(username)){
    			
    				jQuery("#custom-email-error").css('display','block');
    				jQuery("#email").addClass("mage-error");
    				return false;
    		}
    		

      // your code here
    	});
    	function isEmail(email) {
    		  var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    		  return regex.test(email);
    		}
    	
    });
});
</script>
