<?php
$helper         = $this->helper("Lof\Formbuilder\Helper\Fields");
$helper_data = $this->helper("Lof\Formbuilder\Helper\Data");
$form           = $block->getForm();
$field          = $this->getData('field_data');

$field_type     = $field['field_type'];
$label          = $block->filterMessage($field['label']);
$options        = $field['field_options'];
$required       = $field['required'];
$cid              = $helper_data->getFieldId($field);
$inlineCss      = isset($field['inline_css'])?$field['inline_css']:'';
$field_name     = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$frame_work_css = '';
if(isset($field['frame_work_css'])) {
	$frame_work_css	  = $field['frame_work_css'];
}	
$available_fields = $helper->getAvailableFields();
$html             = '';
$field_validate   = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates        = $field_validate;
$field_help 	  = isset($options['description'])?$block->filterMessage($options['description']):'';
if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$image_type = isset($field['image_type'])?$field['image_type']:'png,jpg,gif,jpeg,zip,doc,pdf';
$image_maximum_size = isset($field['image_maximum_size'])?$field['image_maximum_size']:10;

$color_label 	  = isset($options['color_label'])?'color:'.$options['color_label'].';':'';
$color_text 	  = isset($options['color_text'])?'color:'.$options['color_text'].';':'';
$color_description= isset($options['color_description'])?'color:'.$options['color_description'].';':'';
$background_color = isset($options['background_color'])?'background-color:'.$options['background_color'].';':'';

$font_size 		  = isset($options['font_size'])?'font-size:'.(int)$options['font_size'].'px;':'';
$font_style 	  = isset($options['font_style'])?'font-style:'.$options['font_style'].';':'';
$font_weight	  = isset($options['font_weight'])?'font-weight:'.$options['font_weight'].';':'';

if($frame_work_css =='foundation') { ?>
<div class="docs-code-live">
	<div class="row">
		<?php if($label && $label !='') { ?>
		<div class="input-box-label columns medium-6">
			<label for="<?php echo $field_id; ?>" style="<?php echo $font_size.$font_style.$font_weight.$color_label; ?>" class="button <?php echo (1==$required)?'required':''; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
		</div>
		<?php } ?>
		<div class="input-box columns medium-6">
			<input name="<?php echo $field_name; ?>" id="<?php echo $field_id; ?>" style="<?php echo $color_text.$background_color; ?>" title="<?php echo $label; ?>" class="show-for-sr input-text<?php echo (1==$required)?' required-entry':''; ?> <?php echo $validates; ?>" type="file" />
				<?php if($field_help) { ?>
					<span class="help-block" style="<?php echo $color_description; ?>" ><?php echo $field_help; ?></span>
				<?php } ?>
		</div>
	</div>
</div>

<?php
}else {
?>

<div class="subtemplate-wrapper" style="<?php echo $inlineCss ?>">
	<div class="row">
		<?php if($label && $label !='') { ?>
		<div class="input-box-label col-sm-6">
			<label for="<?php echo $field_id; ?>" style="<?php echo $font_size.$font_style.$font_weight.$color_label; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
		</div>
		<?php } ?>
		<div class="input-box col-sm-6">
			<input name="<?php echo $field_name; ?>" id="<?php echo $field_id; ?>" style="<?php echo $color_text.$background_color; ?>" title="<?php echo $label; ?>" class="input-text<?php echo (1==$required)?' required-entry':''; ?> <?php echo $validates; ?>" type="file" />
			<?php if($field_help) { ?>
				<span class="help-block" style="<?php echo $color_description; ?>" ><?php echo $field_help; ?></span>
			<?php } ?>
		</div>
	</div>
</div>
<?php } ?>
