<?php
$helper           = $this->helper("Lof\Formbuilder\Helper\Fields");
$helper_data       = $this->helper("Lof\Formbuilder\Helper\Data");
$form             = $block->getForm();
$form_data        = $this->getData('form_data');
$field            = $this->getData('field_data');
$field_type       = $field['field_type'];
$label            = $block->filterMessage($field['label']);
$inlineCss        = isset($field['inline_css'])?$field['inline_css']:'';
$options          = $field['field_options'];
$required         = $field['required'];
$cid              = $helper_data->getFieldId($field);
$field_name       = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$available_fields = $helper->getAvailableFields();
$html             = '';
$field_validate   = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates        = $field_validate;
$field_help       = isset($options['description'])?$block->filterMessage($options['description']):'';
if($field_validate && is_array($field_validate)) {
    $validates = implode(" ", $field_validate);
}
$width        = isset($field['width'])?$field['width']:'550';
$height       = isset($field['height'])?$field['height']:'400';
$radius       = isset($field['radius'])?(float)$field['radius']:300;
$default_lat  = isset($field['default_lat'])?(float)$field['default_lat']:21.0199438;
$default_long = isset($field['default_long'])?(float)$field['default_long']:105.81731119999995;
$address      = isset($field['address'])?$field['address']:$form_data[$field_name];
$frame_work_css   = '';
if(isset($field['frame_work_css'])) {
    $frame_work_css   = $field['frame_work_css'];
}
if($frame_work_css == 'foundation') {
    $medium = 'columns medium-';
}else{
    $medium = 'col-sm-';
}

$captchaPublicKey = $helper_data->getConfig('googleapi/publickey');
$showLocation     = isset($field['show_location'])?$field['show_location']:0;
$showRadius       = isset($field['show_radius'])?$field['show_location']:0; 
$width            = str_replace("px", "", $width) . "px";
$height           = str_replace("px", "", $height) . "px";

if (!$showRadius) {
    $radius = 0;
}
?>
<div class="subtemplate-wrapper" style="<?php echo $inlineCss ?>">
    <label for="<?php echo $field_id; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo $label; ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
    <div class="row">
        <div <?php if (!$showLocation) { ?>style="display:none"<?php } ?> class="form-group <?php echo $medium; ?>6">
            <div class="row">
                <label class="<?php echo $medium; ?>2 control-label"><?php echo __("Location:"); ?></label>
                <div class="<?php echo $medium; ?>10"><input type="text" class="form-control" name="<?php echo $field_name; ?>" id="<?php echo $field_id."-address"; ?>"  value="<?php echo $address; ?>"/></div>
            </div>
        </div>
        <div <?php if (!$showLocation) { ?>style="display:none"<?php } ?> class="form-group <?php echo $medium; ?>6">
            <div class="row">
                <label class="<?php echo $medium; ?>2 control-label"><?php echo __("Radius:"); ?></label>
                <div class="<?php echo $medium; ?>10"><input type="text" class="form-control" name="<?php echo $field_name."_radius"; ?>" id="<?php echo $field_id."-radius"; ?>" value="<?php echo ($form_data && isset($form_data[$field_name."_radius"]))?$form_data[$field_name."_radius"]:$radius; ?>"/></div>
            </div>
        </div>
    </div>
    <div id="<?php echo $field_id; ?>" style="width: <?php echo $width; ?>; height: <?php echo $height; ?>;margin-top:20px"></div>
    <div class="clearfix">&nbsp;</div>
    <div class="m-t-small">
        <input name="<?php echo $field_name."_lat"; ?>" id="<?php echo $field_id."-lat"; ?>" value="<?php echo ($form_data && isset($form_data[$field_name."_lat"]))?$form_data[$field_name."_lat"]:$default_lat; ?>" class="input-text" type="hidden"/>
        <input name="<?php echo $field_name."_long"; ?>" id="<?php echo $field_id."-long"; ?>" value="<?php echo ($form_data && isset($form_data[$field_name."_long"]))?$form_data[$field_name."_long"]:$default_long; ?>" class="input-text" type="hidden"/>
    </div>
    <div class="clearfix"></div>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false&libraries=places&key=<?php echo $captchaPublicKey ?>"></script>
    <script type="text/javascript">
        require([
            'jquery',
            'Lof_Formbuilder/js/locationpicker/locationpicker'
            ], function(){
                jQuery('#<?php echo $field_id; ?>').locationpicker({
                    location: {latitude: <?php echo $default_lat; ?>, longitude: <?php echo $default_long; ?>},
                    radius: <?php echo $radius; ?>,
                    inputBinding: {
                        latitudeInput: jQuery('#<?php echo $field_id; ?>-lat'),
                        longitudeInput: jQuery('#<?php echo $field_id; ?>-long'),
                        radiusInput: jQuery('#<?php echo $field_id; ?>-radius'),
                        locationNameInput: jQuery('#<?php echo $field_id; ?>-address')
                    },
                    enableAutocomplete: true
                });
            });
        </script>
        <?php if($field_help) { ?>
        <span class="help-block"><?php echo $field_help; ?></span>
        <?php } ?>
    </div>