<?php
$helper         = $this->helper("Lof\Formbuilder\Helper\Fields");
$helper_data = $this->helper("Lof\Formbuilder\Helper\Data");
$form           = $block->getForm();
$field          = $this->getData('field_data');

$field_type     = $field['field_type'];
$label          = $block->filterMessage($field['label']);
$options        = $field['field_options'];
$required       = $field['required'];
$cid              = $helper_data->getFieldId($field);
$inlineCss      = isset($field['inline_css'])?$field['inline_css']:'';
$field_name     = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$frame_work_css = '';
if(isset($field['frame_work_css'])) {
	$frame_work_css	  = $field['frame_work_css'];
}	
$available_fields = $helper->getAvailableFields();
$html             = '';
$field_validate   = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates        = $field_validate;
$field_help 	  = isset($options['description'])?$block->filterMessage($options['description']):'';
if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$image_type = isset($field['image_type'])?$field['image_type']:'png,jpg,gif,jpeg,zip,doc,pdf';
$image_maximum_size = isset($field['image_maximum_size'])?$field['image_maximum_size']:10;
$image_maximum_size = (int)$image_maximum_size*1000000;

$color_label 	  = isset($options['color_label'])?'color:'.$options['color_label'].';':'';
$color_text 	  = isset($options['color_text'])?'color:'.$options['color_text'].';':'';
$color_description= isset($options['color_description'])?'color:'.$options['color_description'].';':'';
$background_color = isset($options['background_color'])?'background-color:'.$options['background_color'].';':'';

$font_size 		  = isset($options['font_size'])?'font-size:'.(int)$options['font_size'].'px;':'';
$font_style 	  = isset($options['font_style'])?'font-style:'.$options['font_style'].';':'';
$font_weight	  = isset($options['font_weight'])?'font-weight:'.$options['font_weight'].';':'';
$file_number_limit = isset($field['file_number_limit'])?(int)$field['file_number_limit']:1;
$show_file_list = isset($field['show_file_list'])?(int)$field['show_file_list']:0;
$drag_drop_text = (isset($field['drag_drop_text']) && $field['drag_drop_text'])?__($field['drag_drop_text']):__('Drag &amp; drop files here');
$open_browser_text = (isset($field['open_browser_text']) && $field['open_browser_text'])?__($field['open_browser_text']):__('Open the file Browser');
if($frame_work_css =='foundation') { ?>
<div class="docs-code-live">
	<div class="row">
		<?php if($label && $label !='') { ?>
		<div class="input-box-label columns medium-6">
			<label for="<?php echo $field_id; ?>Zone" style="<?php echo $font_size.$font_style.$font_weight.$color_label; ?>" class="button <?php echo (1==$required)?'required':''; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
		</div>
		<?php } ?>
		<div class="input-box columns medium-6">
			<div id="<?php echo $field_id; ?>Zone" class="fbd-files-uploader dm-uploader p-5" 
		        data-fieldid="<?php echo $field_id; ?>"
		        data-fieldname="<?php echo $field_name; ?>[]"
		        data-backend="<?php echo $this->getUrl('formbuilder/form/uploader',array("form_id"=>$form->getId())); ?>"
		        data-filetype="<?php echo $image_type;?>"
		        data-fieldclass="show-for-sr input-text<?php echo (1==$required)?' required-entry':''; ?> <?php echo $validates; ?>"
		        data-limitfiles="<?php echo $file_number_limit;?>"
		        data-maxsize="<?php echo $image_maximum_size;?>"
		        style="<?php echo $color_text.$background_color; ?>">
		        <h3 class="mb-5 mt-5 text-muted" style="<?php echo $color_text; ?>"><?php echo $drag_drop_text;?></h3>

		        <div class="btn btn-primary btn-block mb-5">
		            <span><?php echo $open_browser_text;?></span>
		            <input type="file"  id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" title='<?php echo __("Click to add Files");?>' class="input-multi-upload-files show-for-sr input-text<?php echo (1==$required)?' required-entry':''; ?> <?php echo $validates; ?>"/>
		        </div>
		      </div><!-- /uploader -->
		      <?php if($field_help) { ?>
					<span class="help-block" style="<?php echo $color_description; ?>" ><?php echo $field_help; ?></span>
				<?php } ?>
		      <div class="card h-50 <?php echo !$show_file_list?'hidden':'';?>" <?php echo !$show_file_list?'style="display:none;"':'';?>>
		        <div class="card-header">
		          <?php echo __("File List"); ?>
		        </div>
		        <ul class="list-unstyled p-2 d-flex flex-column col" id="files-<?php echo $field_id; ?>">
		          <li class="text-muted text-center empty"><?php echo __("No files uploaded.");?></li>
		        </ul>
		      </div>
		</div>
	</div>
</div>

<?php
}else {
?>

<div class="subtemplate-wrapper" style="<?php echo $inlineCss ?>">
	<div class="row">
		<?php if($label && $label !='') { ?>
		<div class="input-box-label col-sm-6">
			<label for="<?php echo $field_id; ?>Zone" style="<?php echo $font_size.$font_style.$font_weight.$color_label; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
		</div>
		<?php } ?>
		<div class="input-box col-sm-6">
			<!-- Our markup, the important part here! -->
		      <div id="<?php echo $field_id; ?>Zone" class="fbd-files-uploader dm-uploader p-5" 
		        data-fieldid="<?php echo $field_id; ?>"
		        data-fieldname="<?php echo $field_name; ?>"
		        data-backend="<?php echo $this->getUrl('formbuilder/form/uploader',array("form_id"=>$form->getId(),
		      "cid" => $cid)); ?>"
		        data-filetype="<?php echo $image_type;?>"
		        data-fieldclass="show-for-sr input-text<?php echo (1==$required)?' required-entry':''; ?> <?php echo $validates; ?>"
		        data-limitfiles="<?php echo $file_number_limit;?>"
		        data-maxsize="<?php echo $image_maximum_size;?>"
		        style="<?php echo $color_text.$background_color; ?>">
		        <h3 class="mb-5 mt-5 text-muted" style="<?php echo $color_text; ?>"><?php echo $drag_drop_text;?></h3>

		        <div class="btn btn-primary btn-block mb-5">
		            <span><?php echo $open_browser_text;?></span>
		            <input type="file" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" id="" title='<?php echo __("Click to add Files");?>' class="input-multi-upload-files show-for-sr input-text<?php echo (1==$required)?' required-entry':''; ?> <?php echo $validates; ?>"/>
		        </div>
		      </div><!-- /uploader -->
		      <?php if($field_help) { ?>
				<span class="help-block" style="<?php echo $color_description; ?>" ><?php echo $field_help; ?></span>
				<?php } ?>
		      <div class="card h-50 <?php echo !$show_file_list?'hidden':'';?>" <?php echo !$show_file_list?'style="display:none;"':'';?>>
		        <div class="card-header">
		          <?php echo __("File List"); ?>
		        </div>
		        <ul class="list-unstyled p-2 d-flex flex-column col" id="files-<?php echo $field_id; ?>">
		          <li class="text-muted text-center empty"><?php echo __("No files uploaded.");?></li>
		        </ul>
		      </div>
		</div>
	</div>
</div>
<?php } ?>
