<?php
$helper           = $this->helper("Lof\Formbuilder\Helper\Fields");
$dataHelper       = $this->helper("Lof\Formbuilder\Helper\Data");
$form             = $block->getForm();
$form_data        = $this->getData('form_data');
$field            = $this->getData('field_data');
$field_type       = $field['field_type'];
$label            = $block->filterMessage($field['label']);
$options          = $field['field_options'];
$inlineCss        = isset($field['inline_css'])?$field['inline_css']:'';
$required         = $field['required'];
$cid              = $dataHelper->getFieldId($field);
$field_name       = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$available_fields = $helper->getAvailableFields();
$html             = '';
$field_validate   = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates        = $field_validate;
$field_help 	  = isset($options['description'])?$block->filterMessage($options['description']):'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$currency_symbol = $dataHelper->getSymbol();

$size = isset($options['size'])?$options['size']:'';

$color_label 	  = isset($options['color_label'])?'color:'.$options['color_label'].';':'';
$color_text 	  = isset($options['color_text'])?'color:'.$options['color_text'].';':'';
$color_description= isset($options['color_description'])?'color:'.$options['color_description'].';':'';
$background_color = isset($options['background_color'])?'background-color:'.$options['background_color'].';':'';

$border_width	  = isset($options['border_width'])?'border-width:'.(int)$options['border_width'].'px;':'';
$border_radius	  = isset($options['border_radius'])?'border-radius:'.(int)$options['border_radius'].'px;':'';
$border_color	  = isset($options['border_color'])?'border-color:'.$options['border_color'].';':'';
$border_style	  = isset($options['border_style'])?'border-style:'.$options['border_style'].';':'';

$font_size 		  = isset($options['font_size'])?'font-size:'.(int)$options['font_size'].'px;':'';
$font_style 	  = isset($options['font_style'])?'font-style:'.$options['font_style'].';':'';
$font_weight	  = isset($options['font_weight'])?'font-weight:'.$options['font_weight'].';':'';

$icon			  = isset($options['icon'])?$options['icon']:'';
$icon_color		  = isset($options['icon_color'])?$options['icon_color']:'';
$frame_work_css   = '';
if(isset($field['frame_work_css'])) {
	$frame_work_css	  = $field['frame_work_css'];
}
if($frame_work_css == 'foundation') {
	$medium = 'columns medium-';
}else{
	$medium = 'col-sm-';
}

$type  = 'text';
if (isset($field['is_hidden_field']) && $field['is_hidden_field']==1) {
	$type = 'hidden';
}
$attr = '';
if (isset($field['is_readonly']) && $field['is_readonly']==1) {
	$attr = 'readonly';
}

$defaultValue = isset($field['default_value'])?$block->filterMessage($field['default_value']):'';
if ($form_data && isset($form_data[$field_name]) && $form_data[$field_name]!='') {
	$defaultValue = $form_data[$field_name];
}

$label_col = 12;
if(isset($field['fieldcol']) && $field['fieldcol']) {
	if((int)$field['fieldcol'] < 12) {
		$label_col = 12 - (int)$field['fieldcol'];
	}
}
?>
<div class="subtemplate-wrapper form-fieldtype-price" style="<?php echo $inlineCss ?>">
	<div class="input-box">
		<div class="row form-input">
			<div class="subtemplate-inner">
				<?php if($label && $label !='') { ?>
					<div class="form-input1-label <?php echo $medium.$label_col; ?>">
						<label for="<?php echo $field_id; ?>" style="<?php echo $font_size.$font_style.$font_weight.$color_label; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
					</div>
				<?php } ?>
				<div class="form-input1 <?php echo isset($field['fieldcol'])?$medium.$field['fieldcol']:$medium.'12'; ?>">
					<div class="form-currency"><?php echo $currency_symbol; ?></div>
					<input name="<?php echo $field_name; ?>" style="<?php echo $color_text.$background_color.$border_width.$border_radius.$border_color.$border_style; ?>" id="<?php echo $field_id; ?>" title="<?php echo $label; ?>" value="<?= $block->escapeHtmlAttr($this->helper('Lof\Formbuilder\Helper\Data')->getPostValue($field_name) ?: $defaultValue) ?>" placeholder="00.00" class="input-text <?php echo (1==$required)?'required-entry':''; ?> <?php echo $validates; ?> <?php echo $size; ?>" type="<?php echo $type ?>" <?php echo $attr; ?>/>
				</div>
				<?php if($icon) { ?>
				<i class="fa <?php echo $icon; ?> form-field-icon" style="color:<?php echo $icon_color; ?>;"></i>
				<?php } ?>
			</div>
		</div>
		<?php if($field_help) { ?>
		<span class="help-block" style="<?php echo $color_description; ?>"><?php echo $field_help ?></span>
		<?php } ?>
	</div>
</div>