<?php
$helper           = $this->helper("Lof\Formbuilder\Helper\Fields");
$dataHelper       = $this->helper("Lof\Formbuilder\Helper\Data");
$form             = $block->getForm();
$form_data        = $this->getData('form_data');
$field            = $this->getData('field_data');
$field_type       = $field['field_type'];
$label            = $block->filterMessage($field['label']);
$options          = $field['field_options'];
$required         = $field['required'];
$cid              = $dataHelper->getFieldId($field);
$field_name       = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$available_fields = $helper->getAvailableFields();
$field_validate   = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates        = $field_validate;
$field_help 	  = isset($options['description'])?$block->filterMessage($options['description']):'';
$inlineCss        = isset($field['inline_css'])?$field['inline_css']:'';

$color_label 	  = isset($options['color_label'])?'color:'.$options['color_label'].';':'';
$color_text 	  = isset($options['color_text'])?'color:'.$options['color_text'].';':'';
$color_description= isset($options['color_description'])?'color:'.$options['color_description'].';':'';
$background_color = isset($options['background_color'])?'background-color:'.$options['background_color'].';':'';

$font_size 		  = isset($options['font_size'])?'font-size:'.(int)$options['font_size'].'px;':'';
$font_style 	  = isset($options['font_style'])?'font-style:'.$options['font_style'].';':'';
$font_weight	  = isset($options['font_weight'])?'font-weight:'.$options['font_weight'].';':'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$include_other_option = isset($options['include_other_option'])?$options['include_other_option']:0; 

$frame_work_css   = '';
if(isset($field['frame_work_css'])) {
	$frame_work_css	  = $field['frame_work_css'];
}
if($frame_work_css == 'foundation') {
	$medium = 'columns medium-';
}else{
	$medium = 'col-sm-';
}
?>
<div class="subtemplate-wrapper" style="<?php echo $inlineCss ?>">
	<div class="row">
	<?php if($label && $label != '') { ?>
		<div class="input-box-label <?php echo $medium;?>6">
			<label for="<?php echo $field_id; ?>"  style="<?php echo $font_size.$font_style.$font_weight.$color_label; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo $label; ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
		</div>
	<?php } ?>
	<div class="input-box <?php echo $medium;?>6">
		<div class="input-list" style="<?php echo $color_text.$background_color; ?>" >
			<ul class="list-options">
				<?php if($options['options']) {
					foreach($options['options'] as $key=>$val) {
						$item_label = $val['label'];
						$item_checked = $val['checked'];
						if($form_data && isset($form_data[$field_name.$key]) && $form_data[$field_name.$key] == $item_label) {
							$item_checked = true;
						}
						if(!$include_other_option && ($key == (count($options['options']) - 1) )) { ?>
							<li>
								<input type="checkbox" name="<?php echo $field_name.$key.'[]'; ?>" id="<?php echo $field_id.$key; ?>" title="<?php echo $field_name; ?>" value="1" class="<?php echo (1==$required)?'required-entry':''; ?>" <?php echo ($item_checked)?'checked="checked"':''?>/> <label for="<?php echo $field_name.$key; ?>"><?php echo $item_label; ?></label>
							</li>
							<?php } else { ?>
								<li>
									<input type="checkbox" name="<?php echo $field_name.$key.'[]' ?>" id="<?php echo $field_id.$key; ?>" title="<?php echo $field_name; ?>" value="1" <?php echo ($item_checked)?'checked="checked"':''?>/> <label for="<?php echo $field_name.$key; ?>"><?php echo $item_label; ?></label>
								</li>
								<?php }
							} ?>
							<?php } ?>
						</ul>
					</div>
					<?php if($field_help) { ?>
						<span class="help-block"><?php echo $field_help; ?></span>
						<?php } ?>
					</div>
	</div>
</div>