<?php
$helper      = $this->helper("Lof\Formbuilder\Helper\Fields");
$dataHelper       = $this->helper("Lof\Formbuilder\Helper\Data");
$form        = $block->getForm();
$form_data   = $this->getData('form_data');
$field       = $this->getData('field_data');
$field_type  = $field['field_type'];
$label       = $block->filterMessage($field['label']);
$placeholder = isset($field['placeholder'])?$block->filterMessage($field['placeholder']):'';
$options     = $field['field_options'];
$inlineCss   = isset($field['inline_css'])?$field['inline_css']:'';
$required    = $field['required'];
$cid              = $dataHelper->getFieldId($field);
$frame_work_css = '';
if(isset($field['frame_work_css'])) {
	$frame_work_css	  = $field['frame_work_css'];
}
$field_name        = $helper->getFieldPrefix() . $cid . $form->getId();
$field_id          = $field_name.uniqid();
$available_fields  = $helper->getAvailableFields();
$field_validate    = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates         = $field_validate;
$field_help        = isset($options['description'])?$block->filterMessage($options['description']):'';
$validation        = isset($options['validation'])?$options['validation']:'';

$color_label       = isset($options['color_label'])?'color:'.$options['color_label'].';':'';
$color_text        = isset($options['color_text'])?'color:'.$options['color_text'].';':'';
$color_description = isset($options['color_description'])?'color:'.$options['color_description'].';':'';
$background_color  = isset($options['background_color'])?'background-color:'.$options['background_color'].';':'';

$border_width      = isset($options['border_width'])?'border-width:'.(int)$options['border_width'].'px;':'';
$border_radius     = isset($options['border_radius'])?'border-radius:'.(int)$options['border_radius'].'px;':'';
$border_color      = isset($options['border_color'])?'border-color:'.$options['border_color'].';':'';
$border_style      = isset($options['border_style'])?'border-style:'.$options['border_style'].';':'';

$font_size         = isset($options['font_size'])?'font-size:'.(int)$options['font_size'].'px;':'';
$font_style        = isset($options['font_style'])?'font-style:'.$options['font_style'].';':'';
$font_weight       = (isset($options['font_weight']) && $options['font_weight'])?'font-weight:'.$options['font_weight'].';':'';
$defaultValue      = isset($field['default_value'])?$block->filterMessage($field['default_value']):'';
if ($form_data && isset($form_data[$field_name]) && $form_data[$field_name]!='') {
	$defaultValue = $form_data[$field_name];
}

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$size = isset($options['size'])?"rf-size-".$options['size']:'';
$style = '';
if($field['fieldheight']){
	$style = 'height:'.$field['fieldheight'].';';
}
if($frame_work_css != 'foundation') {
	$medium = 'col-sm-';
}elseif($frame_work_css == 'foundation'){
	$medium = 'columns medium-';
}
$type  = 'text';
if (isset($field['is_hidden_field'])) {
	$style = 'display:none;';
}
$attr = '';
if (isset($field['is_readonly'])) {
	$attr = 'readonly';
}
if ($style!='') {
	$style = 'style="' . $style .$color_text.$background_color.$border_width.$border_radius.$border_color.$border_style.'"';
}

$label_col = 12;
if(isset($field['fieldcol']) && $field['fieldcol']) {
	if((int)$field['fieldcol'] < 12) {
		$label_col = 12 - (int)$field['fieldcol'];
	}
}

?>
<div class="subtemplate-wrapper" style="<?php echo $inlineCss ?>">
	<div class="row">
		<?php if ($label && $label != "") { ?>
			<div class="input-box-label <?php echo $medium.$label_col; ?>">
				<label for="<?php echo $field_id; ?>" class="<?php echo (1==$required)?'required':''; ?>" style="<?php echo $font_size.$font_style.$font_weight; ?><?php echo $color_label; ?>"><?php echo __($label); ?><?php echo (1==$required)?'<em>*</em>':'';?></label>
			</div>
		<?php } ?>
		<div class="input-box <?php echo isset($field['fieldcol'])?$medium.$field['fieldcol']:$medium.'12'; ?>">
			<textarea <?php echo $style ?> name="<?php echo $field_name; ?>" <?php if($placeholder) { echo "placeholder='".$placeholder."'"; } ?> id="<?php echo $field_id; ?>" title="<?php echo $label; ?>" class="input-text <?php echo $validation; ?> <?php echo (1==$required)?'required-entry':''; ?> <?php echo $validates; ?> <?php echo $size ?>" <?php echo (isset($options['minlength'])?'data-minlength="'.$options['minlength'].'"':'') ?> <?php echo (isset($options['maxlength'])?'data-maxlength="'.$options['maxlength'].'"':'') ?> <?php echo isset($options['min_max_length_units'])?' data-units="'.$options["min_max_length_units"].'"':'' ?> <?php echo $attr; ?>><?= $block->escapeHtmlAttr($this->helper('Lof\Formbuilder\Helper\Data')->getPostValue($field_name) ?: $defaultValue) ?></textarea>
			<?php
			if($field_help) { ?>
				<span class="help-block" style="<?php echo $color_description; ?>"><?php echo $field_help; ?></span>
				<?php } ?>
			</div>
	</div>
</div>