<div class="table-wrapper query-history">
    <h1 class="table-title"><?= /* @escapeNotVerified */ __('Upcoming Appointments') ?></h1>
    <h5 class="desktop-hide">Appointment Details</h5>
    <table class="data table table-query-items history" id="my-query-table">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Query') ?></caption>
        <thead class="table-head">
            <tr>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date / time') ?></th>
                <th scope="col" class="col service"><?= /* @escapeNotVerified */ __('Service') ?></th>
                <th scope="col" class="col technition"><?= /* @escapeNotVerified */ __('Technition') ?></th>
                <th scope="col" class="col location"><?= /* @escapeNotVerified */ __('Location') ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="table-wrapper query-history">
    <h1 class="table-title"><?= /* @escapeNotVerified */ __('Appointment History') ?></h1>
    <h5 class="desktop-hide">Appointment Details</h5>
    <table class="data table table-query-items history" id="my-query-table">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Query') ?></caption>
        <thead class="table-head">
            <tr>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date / time') ?></th>
                <th scope="col" class="col service"><?= /* @escapeNotVerified */ __('Service') ?></th>
                <th scope="col" class="col technition"><?= /* @escapeNotVerified */ __('Technition') ?></th>
                <th scope="col" class="col location"><?= /* @escapeNotVerified */ __('Location') ?></th>
            </tr>
        </thead>
        <tbody class="tr-color">
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
            <tr>
                <td>10/4/19 - 11:am</td>
                <td>Dermaplanning Treatment</td>
                <td>Natalia</td>
                <td>Bellevue Square</td>
            </tr>
        </tbody>
    </table>
</div>