<?php
$blockObj= $block->getLayout()->createBlock('Magebest\Brand\Block\Product\View');
$product = $block->getProduct();
$product_name = $product->getName();
$title = $product_name;
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
?>
<?php
$brandCollection = $blockObj->getBrandLabel($product); ?>
 <?php $brand = "";?>
<?php if($brandCollection):?>
    <?php $count=0; ?>
    <?php foreach ($brandCollection as $_brand):?>
        <?php if($count<1):?>
            <strong class="brand-label">
                <?php $brand = $_brand->getName();
                $count=$count + 1;
                ?>
            </strong>
        <?php endif; ?>
    <?php endforeach;?>
<?php endif; ?>
<div class="hidden-xs page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
	<?php if ($brand!=""): ?>
	<strong class="brand-label">
	<?= /* @escapeNotVerified */ $brand ?>
	</strong>
	<?php endif; ?>
<h1 class="page-title"
    <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
    <?php if ($block->getAddBaseAttributeAria()): ?>
        aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
    <?php endif; ?>>
    <?= /* @escapeNotVerified */ $product_name ?>
    
</h1>
<?= $block->getChildHtml() ?>
</div>
